modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
modId="notjustbackpacks" #mandatory
version="0.1" #mandatory
displayName="Not Just Backpacks" #mandatory
authors="BlackninjaMM" #optional
description= '''
Where there are backpacks there must be tools to put in it.
'''

[[dependencies.notjustbackpacks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.notjustbackpacks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"